version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Building app..."
      - zip -r app.zip * .[^.]*
artifacts:
  files:
    - app.zip
